### ISSUE TITLE
`NoSuchFieldError: companion` when running `kmmBridgePublish`

### ISSUE THREAD

**Issue by eygraber** [touchlab/KMMBridge#125]
Looks like the issue is probably related to GSON.

```
Caused by: java.lang.NoSuchFieldError: Companion
	at co.touchlab.faktory.internal.GithubCalls.createRelease(GithubCalls.kt:44)
	at co.touchlab.faktory.artifactmanager.GithubReleaseArtifactManager.deployArtifact(GithubReleaseArtifactManager.kt:30)
	at co.touchlab.faktory.KMMBridgePlugin$configureArtifactManagerAndDeploy$uploadTask$1$2.execute(KMMBridge.kt:119)
	at co.touchlab.faktory.KMMBridgePlugin$configureArtifactManagerAndDeploy$uploadTask$1$2.execute(KMMBridge.kt:115)
```

**Comment by russhwolf** [comment]
Are you setting `GITHUB_REPO` and `GITHUB_PUBLISH_TOKEN` environment variables? It'd help to know more about your configuration as I don't think any of us have seen this particular error.

**Comment by eygraber** [comment]
We're using the [kmmbridge provided GitHub Actions workflow](https://github.com/touchlab/KMMBridgeGithubWorkflow/blob/main/.github/workflows/faktorybuild.yml#L62).

The stacktrace is kind of confusing because it says that the error occurs in kmmbridge's code, and not in GSON or OKHttp. It's almost as if the `String.toRequestBody` companion extension from OKHttp is causing the issue, but I don't know why that would happen.

In any case, we stopped using GitHub releases for this, so it's kind of difficult to test.

**Comment by russhwolf** [comment]
Since we're not as focused on this configuration anymore and you're no longer using it, I'm going to close this

**Comment by mrikirill** [comment]
Getting the same issue
Tried to execute `kmmBridgePublish` locally

```
 ./gradlew kmmBridgePublish -PGITHUB_PUBLISH_TOKEN={my-token} -PGITHUB_REPO={my-repo} --stacktrace

```

Output:
```
Caused by: java.lang.NoSuchFieldError: Companion
        at co.touchlab.faktory.internal.GithubCalls.createRelease(GithubCalls.kt:44)
        at co.touchlab.faktory.artifactmanager.GithubReleaseArtifactManager.deployArtifact(GithubReleaseArtifactManager.kt:30)
        at co.touchlab.faktory.KMMBridgePlugin$configureArtifactManagerAndDeploy$uploadTask$1$2.execute(KMMBridge.kt:139)

```

Any ideas did I miss something?
spmDevBuild works well
```
./gradlew spmDevBuild
```
