### ISSUE TITLE
Execution failed for task ':updatePackageSwift'.

### ISSUE THREAD

**Issue by developer--** [touchlab/KMMBridge#248]
## Summary

I'm trying to publish KMM module for iOS but **iOS Publish** action fails with an error

## Details

KMMBridge plugin version 0.5.5
```
Task :linkReleaseFrameworkIosX64
> Task :assembleReleaseIosSimulatorFatFrameworkForCoreXCFramework
> Task :assembleCoreReleaseXCFramework
xcframework successfully written out to: /Users/runner/work/sample-kmm-core/sample-kmm-core/build/XCFrameworks/release/core.xcframework
> Task :zipXCFramework
> Task :publishKMMBridgeFrameworkPublicationToGitHubPackagesRepository
> Task :uploadXCFramework
> Task :updatePackageSwift FAILED
16 actionable tasks: 16 executed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':updatePackageSwift'.
> java.io.FileNotFoundException: /Package.swift (Read-only file system)
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':updatePackageSwift'.

....
Caused by: java.io.FileNotFoundException: /Package.swift (Read-only file system)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
	at co.touchlab.faktory.dependencymanager.SpmDependencyManager.writePackageFile(SpmDependencyManager.kt:132)
	at co.touchlab.faktory.dependencymanager.SpmDependencyManager.access$writePackageFile(SpmDependencyManager.kt:42)
	at co.touchlab.faktory.dependencymanager.SpmDependencyManager$configure$updatePackageSwiftTask$1$1.execute(SpmDependencyManager.kt:89)
	at co.touchlab.faktory.dependencymanager.SpmDependencyManager$configure$updatePackageSwiftTask$1$1.execute(SpmDependencyManager.kt:78)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:835)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:808)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
	... 114 more

```
After the pipeline error, when I go to github packages, there is KMM package published, but I don't know if it is ok or not
## Reproduction

I tried to inlcude `Package.swift` file at the same level as `gradle.build.kts` file is, but error is same (when running it without Package.swift file)
```
addGithubPackagesRepository()
kmmbridge {
    mavenPublishArtifacts()
    spm()
}
```
## Expected result

Github action successfull result

## Current state

Github action fails

**Comment by kpgalligan** [comment]
Closing for now. The samples and versions of KMMBridge have been updated. The error above seems to have guessed that the repo root is the file system root, which would mean the internal git call to find the git repo root was *possibly* happening outside of a git repo. For example, if the source was cloned, then copied, or if the build was happening from a zip instead of cloning with git. That, or there's some error from git. The git call doesn't throw if it fails because it runs during config, and if you had a new project that wasn't yet in a git repo, your project would fail to load in an IDE or fail to run any Gradle tasks.

If anybody runs into this, please let us know. Also, to avoid this, add a relative path param to the `spm()` call in KMMBridge config. Probably just `spm(".")`, but that would need to be tested to confirm.
